language: go
go:
  - "1.25.1"

services:
  - docker

notifications:
  email: false

env:
  - GOTIFY_VERSIONS="v2.9.0"

before_install:
  - go install github.com/gotify/plugin-api/cmd/gomod-cap@latest

script:
  - go test ./...

before_deploy:
  - >
    for TARGET in $GOTIFY_VERSIONS; do
      make GOTIFY_VERSION="$TARGET" FILE_SUFFIX="-for-gotify-$TARGET" build;
    done

deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: build/*.so
    skip_cleanup: true
    on:
      tags: true